### PR TITLE
Fix LinuxUtilImplementation of:

### PR DESCRIPTION
**Pull request by toschneck**
* Focus application
* Closing application
* Make  output and control of native commands more flexible

### CODE REVIEW

**Comment by RaiMan** [comment]
wow, looks like some work.

Is it tested sufficiently, so I can just merge it without having a bad conscience ;-) ?

I want to release the 1.1.1 before end of 2015.

**Comment by toschneck** [comment]
Hi, I tested it under ubuntu and centos there it works well. I think this should then also fit for the most other common linux distribution as well.

**Comment by RaiMan** [comment]
ok, thanks. have some overload currently ;-)

**Comment by toschneck** [comment]
No hurry, i already use my forked version, so I`m fine ;-)

**Pull request merged**
