### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by sarkershantonu**

### CODE REVIEW

**Comment by RaiMan** [comment]
I do not want such information in the README.

Please post as issues (as you did with version 2), so it can be discussed and tracked.

**Comment by RaiMan** [comment]
your mail (your github) does not work:
Delivery to the following recipients failed: shantonu_oxxford@yahoo.com

----- content
Hi,
I have switched your README pull request to an issue.
I would appreciate, if you would comment some of your statements a bit 
more in detail, to get them clearer about the intention.
See my comments. 
https://github.com/RaiMan/SikuliX-2014/issues/202
Raimund

**Comment by sarkershantonu** [comment]
hi

Sorry for typo, my email , shantonu_oxford@yahoo.com
I am changing pom as well as distribution packaging according to our need. If you allow, i can send you to amend with existing POM. 
Thanks
Shantonu

**Comment by RaiMan** [comment]
ok. thanks

**Pull request closed without merging**
